# VMD / psfgen helper: rebuild MT-ND1 and apply LHON mutation m.3460G>A (p.Ala52Thr, A52T)
#
# Usage:
#   vmd -dispdev text -e vmd_psfgen_mutate_nd1_A52T.tcl
#
# Requirements:
#   - VMD with psfgen
#   - CHARMM36 protein topology file (e.g., top_all36_prot.rtf)
#
# Inputs (generated by build_complexI_9TI4_models.py):
#   - nd1_chain_s_WT_heavy.pdb
#
# Outputs:
#   - nd1_chain_s_A52T.psf
#   - nd1_chain_s_A52T_rebuilt.pdb

package require psfgen

# Point this to your CHARMM36 topology. Option A: set env var before running VMD:
#   export CHARMM_TOP=/path/to/top_all36_prot.rtf
if {[info exists env(CHARMM_TOP)]} {
  topology $env(CHARMM_TOP)
} else {
  topology top_all36_prot.rtf
}

set in_pdb  "nd1_chain_s_WT_heavy.pdb"
set out_psf "nd1_chain_s_A52T.psf"
set out_pdb "nd1_chain_s_A52T_rebuilt.pdb"

resetpsf

# Build ND1 as a standalone segment.
segment ND1 {
  pdb $in_pdb
}
coordpdb $in_pdb ND1

# Apply the mutation at residue 52: ALA -> THR (A52T).
mutate ND1 52 THR

# Fill in missing atoms (e.g., OG1/CG2 + hydrogens) using internal coordinates.
guesscoord

writepsf $out_psf
writepdb $out_pdb

quit

