# VMD / psfgen helper: rebuild MT-ND4 and apply LHON mutation m.11778G>A (p.Arg340His, R340H)
#
# Usage:
#   vmd -dispdev text -e vmd_psfgen_mutate_nd4_R340H.tcl
#
# Requirements:
#   - VMD with psfgen
#   - CHARMM36 protein topology file (e.g., top_all36_prot.rtf)
#
# Inputs (generated by build_complexI_9TI4_models.py):
#   - nd4_chain_r_WT_heavy.pdb
#
# Outputs:
#   - nd4_chain_r_R340H.psf
#   - nd4_chain_r_R340H_rebuilt.pdb

package require psfgen

# Point this to your CHARMM36 topology. Option A: set env var before running VMD:
#   export CHARMM_TOP=/path/to/top_all36_prot.rtf
if {[info exists env(CHARMM_TOP)]} {
  topology $env(CHARMM_TOP)
} else {
  topology top_all36_prot.rtf
}

set in_pdb  "nd4_chain_r_WT_heavy.pdb"
set out_psf "nd4_chain_r_R340H.psf"
set out_pdb "nd4_chain_r_R340H_rebuilt.pdb"

resetpsf

# Build ND4 as a standalone segment.
segment ND4 {
  pdb $in_pdb
}
coordpdb $in_pdb ND4

# Apply the mutation at residue 340: ARG -> HIS (R340H).
#
# Note: many CHARMM topologies use HSD/HSE/HSP (not HIS). We try HIS first and fall back to HSE.
set mut_ok 0
set err1 ""
set err2 ""
if {![catch {mutate ND4 340 HIS} err1]} {
  set mut_ok 1
} else {
  if {![catch {mutate ND4 340 HSE} err2]} {
    set mut_ok 1
  }
}
if {!$mut_ok} {
  puts "ERROR: could not mutate residue 340 to HIS/HSE."
  puts "  HIS error: $err1"
  puts "  HSE error: $err2"
  puts "Edit this script to use HSD/HSP if needed for your topology."
  quit
}

# Fill in missing atoms (e.g., HIS ring atoms + hydrogens) using internal coordinates.
guesscoord

writepsf $out_psf
writepdb $out_pdb

quit

