# VMD / psfgen helper: rebuild MT-ND6 and apply LHON mutation m.14484T>C (p.Met64Val, M64V)
#
# Usage:
#   vmd -dispdev text -e vmd_psfgen_mutate_nd6_M64V.tcl
#
# Requirements:
#   - VMD with psfgen
#   - CHARMM36 protein topology file (e.g., top_all36_prot.rtf)
#
# Inputs (generated by build_complexI_9TI4_models.py):
#   - nd6_chain_m_WT_heavy.pdb
#
# Outputs:
#   - nd6_chain_m_M64V.psf
#   - nd6_chain_m_M64V_rebuilt.pdb

package require psfgen

# Point this to your CHARMM36 topology. Option A: set env var before running VMD:
#   export CHARMM_TOP=/path/to/top_all36_prot.rtf
if {[info exists env(CHARMM_TOP)]} {
  topology $env(CHARMM_TOP)
} else {
  topology top_all36_prot.rtf
}

set in_pdb  "nd6_chain_m_WT_heavy.pdb"
set out_psf "nd6_chain_m_M64V.psf"
set out_pdb "nd6_chain_m_M64V_rebuilt.pdb"

resetpsf

# Build ND6 as a standalone segment.
segment ND6 {
  pdb $in_pdb
}
coordpdb $in_pdb ND6

# Apply the mutation at residue 64: MET -> VAL (M64V).
mutate ND6 64 VAL

# Fill in missing atoms (e.g., VAL CG2 + hydrogens) using internal coordinates.
guesscoord

writepsf $out_psf
writepdb $out_pdb

quit

